import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ttNorms = localFont({
  src: "./fonts/TTNorms/TT Norms Pro Regular.otf",
  variable: "--font-norms-sans",
  weight: "100",
});

export const ttNormsMed = localFont({
  src: "./fonts/TTNorms/TT Norms Pro Medium.otf",
  variable: "--font-norms-med-sans",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ttNorms.variable} ${ttNormsMed.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
